web:
 build: .
 ports:
  - "8080:8080"
 links:
  - postgres
test:
 build: .
 volumes:
  - ./:/code
 links:
  - postgres:dockerhost
 working_dir: /code
 entrypoint: ["./scripts/runtests"]
postgres:
 image: postgres
 environment:
  - POSTGRES_PASSWORD=testbox
